window:
  dimensions:
    columns: 109
    lines: 29
  padding:
    x: 0
    y: 0
    class:
      instance: Alacritty
      general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

window.opacity: 1

font:
  normal:
    family: firacode
    style: Medium
  ligatures: true
  bold:
    family: firacode
    style: Bold
  italic:
    family: firacode
    style: MediumItalic
  bold_italic:
    family: firacode
    style: BoldItalic
  size: 13
draw_bold_text_with_bright_colors: true    

