[font]
size = 13

[font.bold]
family = "firacode"
style = "Bold"

[font.bold_italic]
family = "firacode"
style = "BoldItalic"

[font.italic]
family = "firacode"
style = "MediumItalic"

[font.normal]
family = "firacode"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 109
lines = 29

[window.padding]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[window]
opacity = 0.9
